include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_single_quotes
    - always_declare_return_types
    - avoid_print
    - sort_child_properties_last
    - unnecessary_this

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
